FROM golang:1.23-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app-bin .

FROM scratch

WORKDIR /app

COPY --from=build /app/app-bin .

ENTRYPOINT ["/app/app-bin"]
