FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app-bin .

RUN apk --no-cache add ca-certificates tzdata

ENTRYPOINT ["/app/app-bin"]
